version: '3.7'
services:
  app:
    image: node:20
    volumes:
      - ./:/app
    working_dir: /app
    tty: true
    stdin_open: true
    command: bash -c "npm install && npm run dev"
    environment:
      - CYPRESS_baseUrl=http://cypress:3000
    ports:
      - '3000:3000'

  cypress:
    image: cypress/included:6.0.0
    depends_on:
      - app
    volumes:
      - ./cypress:/cypress
      - ./cypress.json:/cypress.json
    working_dir: /cypress/e2e
    command: 'npm run cy:run'

volumes:
  node_modules:
