import type { Metadata } from 'next';
import './globals.css';
import { StoreProvider } from '@/store/StoreProvider';
import { ThemeProvider } from '@emotion/react';
import theme from './theme';

export const metadata: Metadata = {
  title: 'Mitarbeiterverzeichnis',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider>
      <html lang="de">
        <body>
          {/* <ThemeProvider theme={theme}>{children}</ThemeProvider> */}
          {children}
        </body>
      </html>
    </StoreProvider>
  );
}
